import { useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { Download, FileText, Plus, Printer } from 'lucide-react';
import { useAuth } from '../auth';
import { BillingStatus, PageHeader, TypeBadge, branchName, useMeta } from '../Shell';
import { api, ApiError, saveBlob } from '../lib/api';
import { date, money, todayISO } from '../lib/format';
import { useApi, useDebounced } from '../lib/useApi';
import type { InvoiceDetail, InvoiceSummary, Paged } from '../lib/types';
import { Button } from '../ui/Button';
import { Card } from '../ui/Card';
import { Dropdown, DropdownItem } from '../ui/Dropdown';
import { EmptyState } from '../ui/EmptyState';
import { ErrorState } from '../ui/ErrorState';
import { Input, SearchInput, Select } from '../ui/Input';
import { PageSkeleton } from '../ui/Skeleton';
import { Pagination, Table, type Column } from '../ui/Table';
import { useToast } from '../ui/ToastContext';
import { InvoiceDocument } from './InvoiceDocument';

export function Invoices() {
  const { can } = useAuth();
  const meta = useMeta();
  const navigate = useNavigate();
  const { showToast } = useToast();
  const [params, setParams] = useSearchParams();
  const [q, setQ] = useState(params.get('q') ?? '');
  const search = useDebounced(q);
  const filters = {
    type: params.get('type') ?? '',
    payment_status: params.get('payment_status') ?? '',
    branch_key: params.get('branch_key') ?? '',
    date_from: params.get('date_from') ?? '',
    date_to: params.get('date_to') ?? '',
  };
  const page = Number(params.get('page') ?? 1);
  const setFilter = (k: string, v: string) => {
    const next = new URLSearchParams(params);
    if (v) next.set(k, v); else next.delete(k);
    next.delete('page');
    setParams(next, { replace: true });
  };
  const list = useApi(() => api.get<Paged<InvoiceSummary>>('/invoices', { ...filters, q: search, page }), [params.toString(), search]);

  const exportCsv = async (type: string) => {
    try {
      saveBlob(await api.blob('/invoices/export', { type }), `${type}_invoices_${todayISO()}.csv`);
    } catch (err) {
      showToast(err instanceof ApiError ? err.message : 'Export failed.', 'error');
    }
  };

  const columns: Column<InvoiceSummary>[] = [
    { key: 'number', header: 'Invoice no.', render: (i) => <Link to={`/invoices/${i.id}`} className="font-medium text-primary hover:underline">{i.invoice_number}</Link> },
    { key: 'type', header: 'Type', render: (i) => <TypeBadge type={i.invoice_type} /> },
    { key: 'date', header: 'Date', render: (i) => <span className="whitespace-nowrap">{date(i.invoice_date)}</span> },
    { key: 'customer', header: 'Customer', render: (i) => <span className="text-text">{i.billing_name}</span> },
    { key: 'branch', header: 'Branch', render: (i) => branchName(meta, i.branch_key) },
    { key: 'total', header: 'Amount', align: 'right', render: (i) => <span className="font-medium tabular-nums">{money(i.grand_total, true)}</span> },
    { key: 'status', header: 'Status', render: (i) => <BillingStatus status={i.payment_status} /> },
    { key: 'by', header: 'Generated by', render: (i) => <span className="text-text-muted">{i.created_by_name || '—'}</span> },
  ];

  const canBoth = can('invoices.view') && can('invoices.view_proforma');
  return (
    <>
      <PageHeader
        title="Invoices"
        description="Tax and proforma invoices."
        actions={
          <>
            {can('invoices.export') && (
              <Dropdown label="Export" width="w-52" triggerClassName="h-9 gap-2 border border-border bg-surface px-3.5 text-sm hover:bg-surface-secondary"
                trigger={<><Download size={16} aria-hidden="true" /> Export CSV</>}>
                <DropdownItem onClick={() => exportCsv('invoice')}>Tax invoices</DropdownItem>
                {can('invoices.view_proforma') && <DropdownItem onClick={() => exportCsv('proforma')}>Proforma invoices</DropdownItem>}
              </Dropdown>
            )}
            {can('invoices.view') && <Button variant="secondary" onClick={() => navigate('/invoices/print')}><Printer size={16} /> Print by date</Button>}
            {(can('invoices.create_tax') || can('invoices.create_proforma')) && <Button onClick={() => navigate('/invoices/new')}><Plus size={16} /> New invoice</Button>}
          </>
        }
      />
      <Card>
        <div className="flex flex-wrap items-end gap-3 border-b border-border p-4">
          <SearchInput label="Search invoices" placeholder="Number, customer or GSTIN" value={q} onChange={(v) => { setQ(v); setFilter('page', ''); }} />
          {canBoth && (
            <Select label="Type" value={filters.type} onChange={(e) => setFilter('type', e.target.value)}>
              <option value="">All types</option>
              <option value="invoice">Tax invoices</option>
              <option value="proforma">Proforma</option>
            </Select>
          )}
          {can('invoices.view') && (
            <Select label="Payment" value={filters.payment_status} onChange={(e) => setFilter('payment_status', e.target.value)}>
              <option value="">Any</option>
              <option value="unpaid">Unpaid</option>
              <option value="partial">Part paid</option>
              <option value="paid">Paid</option>
              <option value="not_tracked">Not tracked</option>
            </Select>
          )}
          <Select label="Branch" value={filters.branch_key} onChange={(e) => setFilter('branch_key', e.target.value)}>
            <option value="">All branches</option>
            {meta.branches.map((b) => <option key={b.key} value={b.key}>{b.display_name}</option>)}
          </Select>
          <Input label="From" type="date" value={filters.date_from} onChange={(e) => setFilter('date_from', e.target.value)} />
          <Input label="To" type="date" value={filters.date_to} onChange={(e) => setFilter('date_to', e.target.value)} />
        </div>
        {list.status === 'error' ? <ErrorState message={list.error} onRetry={list.reload} /> : (
          <>
            <Table columns={columns} rows={list.data?.items ?? []} rowKey={(i) => String(i.id)} loading={list.loading}
              onRowClick={(i) => navigate(`/invoices/${i.id}`)}
              empty={<EmptyState icon={FileText} title="No invoices found" description="Try a different search or filter." />} />
            {list.data && <Pagination page={page} pageSize={list.data.page_size} total={list.data.total} noun="invoices"
              onChange={(p) => setFilter('page', String(p))} />}
          </>
        )}
      </Card>
    </>
  );
}

/** bulk_invoice_date_range.php: every tax invoice in a date range, printed (or saved as one PDF) at once. */
export function PrintBatch() {
  const [range, setRange] = useState({ date_from: todayISO().slice(0, 8) + '01', date_to: todayISO() });
  const [loaded, setLoaded] = useState(range);
  const batch = useApi(() => api.get<InvoiceDetail[]>('/invoices/batch', loaded), [loaded]);

  return (
    <>
      <PageHeader
        crumb={{ label: 'Invoices', to: '/invoices' }}
        title="Print invoices by date"
        description="Loads every tax invoice in the range. Print, or choose Save as PDF in the print dialog."
        actions={<Button onClick={() => window.print()} disabled={!batch.data?.length}><Printer size={16} /> Print {batch.data?.length ?? ''} invoices</Button>}
      />
      <Card className="no-print mb-5">
        <form className="flex flex-wrap items-end gap-3 p-4" onSubmit={(e) => { e.preventDefault(); setLoaded(range); }}>
          <Input label="From" type="date" value={range.date_from} onChange={(e) => setRange((r) => ({ ...r, date_from: e.target.value }))} />
          <Input label="To" type="date" value={range.date_to} onChange={(e) => setRange((r) => ({ ...r, date_to: e.target.value }))} />
          <Button type="submit" variant="secondary">Load invoices</Button>
        </form>
      </Card>
      {batch.status === 'error' ? <ErrorState message={batch.error} onRetry={batch.reload} />
        : !batch.data ? <PageSkeleton />
          : batch.data.length === 0 ? <EmptyState icon={FileText} title="No tax invoices in this range" />
            : <div className="space-y-6">{batch.data.map((i) => <InvoiceDocument key={i.id} invoice={i} />)}</div>}
    </>
  );
}
