import { useMeta } from '../Shell';
import { date, money } from '../lib/format';
import type { InvoiceDetail } from '../lib/types';

// view_invoice.php strips the field labels its old address form embedded in the text.
const ADDRESS_LABEL = /^(Building No\.\/Flat No\.|Name Of Premises\/Building|Road\/Street|Nearby Landmark|Locality\/Sub Locality|City\/Town\/Village|District|State|PIN Code):\s*/i;
const cleanAddress = (a: string) => a.split('\n').map((l) => l.trim().replace(ADDRESS_LABEL, '')).filter(Boolean).join(', ');

const rs = (v: number) => money(v, true);

/** The printed invoice. Always light: it is a paper document. */
export function InvoiceDocument({ invoice: inv }: { invoice: InvoiceDetail }) {
  const { branches, settings } = useMeta();
  const branch = branches.find((b) => b.key === inv.branch_key) ?? branches[0];
  const label = inv.invoice_type === 'invoice' ? 'Tax Invoice' : 'Proforma Invoice';

  return (
    <article className="doc mx-auto w-full min-w-0 max-w-[860px] rounded-lg border border-gray-200 p-6 text-[13px] leading-relaxed shadow-sm sm:p-10">
      <header className="flex flex-col gap-6 border-b-2 border-gray-900 pb-5 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <img src="/logo_web.png" alt="Rexera" className="h-10 w-auto" />
          <h1 className="mt-4 text-2xl font-bold uppercase tracking-wide text-gray-900">{label}</h1>
        </div>
        <div className="sm:max-w-[55%] sm:text-right">
          <h2 className="text-sm font-bold text-gray-900">{branch?.legal_name}</h2>
          <p className="text-gray-600">GSTIN: {settings.company_gstin}</p>
          <p className="text-gray-600">Phone: {branch?.phone}</p>
          <p className="text-gray-600">{branch?.address}</p>
        </div>
      </header>

      <section className="grid gap-6 py-5 sm:grid-cols-2">
        <div>
          <p className="text-[11px] font-semibold uppercase tracking-wider text-gray-500">Billing to</p>
          <p className="mt-1 text-base font-semibold text-gray-900">{inv.billing_name}</p>
          <p className="text-gray-700">{cleanAddress(inv.billing_address)}</p>
          <div className="mt-1 text-gray-700">
            {inv.billing_phone && <p><span className="font-medium">Phone:</span> {inv.billing_phone}</p>}
            {inv.client_gstin && <p><span className="font-medium">GSTIN:</span> {inv.client_gstin}</p>}
            {inv.client_state && <p><span className="font-medium">State:</span> {inv.client_state}</p>}
          </div>
        </div>
        <div className="sm:text-right">
          <p className="text-[11px] font-semibold uppercase tracking-wider text-gray-500">Invoice details</p>
          <p className="mt-1 text-gray-700">Invoice number</p>
          <p className="text-base font-semibold text-gray-900">{inv.invoice_number}</p>
          <p className="mt-1 text-gray-700">Invoice date: <span className="font-medium text-gray-900">{date(inv.invoice_date)}</span></p>
          {inv.created_by_name && <p className="text-xs text-gray-500">Generated by: {inv.created_by_name}</p>}
        </div>
      </section>

      <div className="overflow-x-auto">
        <table className="w-full min-w-[520px] border-collapse text-left">
          <thead>
            <tr className="bg-gray-900 text-[11px] uppercase tracking-wider text-white">
              <th className="px-3 py-2 text-center">S.No</th>
              <th className="px-3 py-2">Particulars</th>
              <th className="px-3 py-2">HSN</th>
              <th className="px-3 py-2 text-right">Qty</th>
              <th className="px-3 py-2 text-right">Rate</th>
              <th className="px-3 py-2 text-right">Amount</th>
            </tr>
          </thead>
          <tbody>
            {inv.items.map((it, i) => (
              <tr key={it.id} className="border-b border-gray-200">
                <td className="px-3 py-2 text-center">{i + 1}</td>
                <td className="px-3 py-2 font-medium text-gray-900">{it.particulars}</td>
                <td className="px-3 py-2">{it.hsn}</td>
                <td className="px-3 py-2 text-right tabular-nums">{Number(it.quantity)}</td>
                <td className="px-3 py-2 text-right tabular-nums">{rs(it.rate)}</td>
                <td className="px-3 py-2 text-right tabular-nums">{rs(it.amount)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <section className="mt-6 grid gap-6 sm:grid-cols-[1fr_300px]">
        <div className="space-y-4">
          <div className="rounded-md border border-gray-200 p-4">
            <p className="text-[11px] font-semibold uppercase tracking-wider text-gray-500">Bank details</p>
            <div className="mt-2 flex items-start justify-between gap-4">
              <div className="space-y-0.5 text-gray-700">
                <p><span className="font-medium">Account name:</span> {inv.bank_account_name || settings.bank_account_name}</p>
                <p><span className="font-medium">Account no:</span> {inv.bank_account_number || settings.bank_account_number}</p>
                <p><span className="font-medium">IFSC code:</span> {inv.bank_ifsc_code || settings.bank_ifsc_code}</p>
                {inv.bank_upi_id && <p><span className="font-medium">UPI ID:</span> {inv.bank_upi_id}</p>}
              </div>
              <img src="/qr_code.jpg" alt="UPI QR code" className="h-24 w-24 shrink-0 object-contain" />
            </div>
          </div>
          {inv.remark && (
            <div className="rounded-md border border-gray-200 p-4">
              <p className="text-[11px] font-semibold uppercase tracking-wider text-gray-500">Remark / terms</p>
              <p className="mt-1 whitespace-pre-line text-gray-700">{inv.remark}</p>
            </div>
          )}
        </div>
        <div>
          <dl className="space-y-1.5 text-gray-700">
            <div className="flex justify-between"><dt>Sub-total</dt><dd className="tabular-nums">{rs(inv.sub_total)}</dd></div>
            {Number(inv.cgst_amount) > 0 && (
              <>
                <div className="flex justify-between"><dt>CGST ({Number(inv.cgst_rate)}%)</dt><dd className="tabular-nums">{rs(inv.cgst_amount)}</dd></div>
                <div className="flex justify-between"><dt>SGST ({Number(inv.sgst_rate)}%)</dt><dd className="tabular-nums">{rs(inv.sgst_amount)}</dd></div>
              </>
            )}
            {Number(inv.igst_amount) > 0 && (
              <div className="flex justify-between"><dt>IGST ({Number(inv.igst_rate)}%)</dt><dd className="tabular-nums">{rs(inv.igst_amount)}</dd></div>
            )}
          </dl>
          <div className="mt-3 flex justify-between border-t-2 border-gray-900 pt-2 text-base font-bold text-gray-900">
            <span>Grand total</span>
            <span className="tabular-nums">{rs(inv.grand_total)}</span>
          </div>
          <div className="mt-8 text-center">
            <img src="/stamp.png" alt="Company stamp" className="mx-auto h-24 w-24 object-contain opacity-90" />
            <p className="mt-1 border-t border-gray-300 pt-1 text-xs font-medium text-gray-700">Authorized Signatory</p>
          </div>
        </div>
      </section>
      <p className="mt-8 text-center text-[11px] text-gray-500">This is a computer generated invoice.</p>
    </article>
  );
}
